/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 purple_dragon.glb --transform 
Files: purple_dragon.glb [32.24MB] > D:\Code\Fiverr\anim-form\public\models\purple_dragon-transformed.glb [3.49MB] (89%)
Author: Kyan0s (https://sketchfab.com/kyan0s)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/enchanted-dark-dragon-59c1bf78e8b543299d2d68581d2e6c0d
Title: Enchanted Dark Dragon
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials, animations } = useGLTF(
    "/purple_dragon-transformed.glb"
  );
  const group = useRef();
  let mixer, action;

  const modelAnimations = () => {
    mixer = new THREE.AnimationMixer(group.current);
    const clip = animations[0];
    action = mixer.clipAction(clip);
    action.play();
    action.loop = THREE.LoopRepeat;
    mixer.update(0.03);
    updateMixer();
  };

  const updateMixer = () => {
    mixer.update(0.025);
    //add some wait

    requestAnimationFrame(updateMixer);
  };

  useEffect(() => {
    if (group.current) modelAnimations();
    console.log("group.current", group.current);
  }, [group.current]);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <primitive object={nodes.Armature_rootJoint} />
        <skinnedMesh
          name='Circle_0'
          geometry={nodes.Circle_0.geometry}
          material={materials.drgnHrn}
          skeleton={nodes.Circle_0.skeleton}
          position={[0, 2.3, -2.4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
        <skinnedMesh
          name='mouth_0'
          geometry={nodes.mouth_0.geometry}
          material={materials.drgnMth}
          skeleton={nodes.mouth_0.skeleton}
          position={[0, 2.3, -2.4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
        <skinnedMesh
          name='theeth_0'
          geometry={nodes.theeth_0.geometry}
          material={materials.drgnThht}
          skeleton={nodes.theeth_0.skeleton}
          position={[0, 2.3, -2.4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
        <skinnedMesh
          name='HPCreature002_0'
          geometry={nodes.HPCreature002_0.geometry}
          material={materials.drgnClws}
          skeleton={nodes.HPCreature002_0.skeleton}
          position={[0, 2.3, -2.4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
        <skinnedMesh
          name='HPCreature001_0'
          geometry={nodes.HPCreature001_0.geometry}
          material={materials.drgnSkn}
          skeleton={nodes.HPCreature001_0.skeleton}
          position={[0, 2.3, -2.4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/purple_dragon-transformed.glb");
