import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/Navbar";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={"max-w-screen overflow-x-hidden"}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
