export const IMAGE_STYLES = [
  "Airbrush Art",
  "Anime",
  "Art Nouveau",
  "Blender Render",
  "Blueprint",
  "Cartoon",
  "Chalk Drawing",
  "Charcoal Drawing",
  "Crayon Drawing",
  "Digital Oil Painting",
  "GTA",
  "Graffiti",
  "Impressionism",
  "Ink Drawing",
  "Line Art",
  "Low-Poly Art",
  "Neon Art",
  "Origami",
  "Photorealism",
  "Pixel Art",
  "Pop Art",
  "Psychedelic Art",
  "Silhouette Illustration",
  "Steampunk",
  "Wood Carving",
];
