export const INITIAL_CHARACTER = {
  race: {
    name: "",
    gender: null,
  },
  class: null,
  abilities: {
    strength: 8,
    dexterity: 8,
    constitution: 8,
    intelligence: 8,
    wisdom: 8,
    charisma: 8,
  },
  background: null,
  personality: {
    ideal: null,
    bond: null,
    personality: null,
    flaw: null,
  },
  alignment: null,
  equipment: {
    weapon: null,
    secondary: null,
    armor: null,
    "tool&ammo": null,
  },
  gold: null,
  name: "",
  pointsToSpend: 27,
};
export const dummy = {
  race: {
    name: "Arakocra",
    gender: "female",
  },
  class: "Barbarian",
  abilities: {
    strength: 8,
    dexterity: 8,
    constitution: 8,
    intelligence: 8,
    wisdom: 8,
    charisma: 8,
  },
  background: "Dungeon Delver",
  personality: {
    ideal: "freedom",
    bond: "family",
    personality: "Adventurous",
    flaw: "addiction",
  },
  alignment: "true good",
  equipment: {
    weapon: "Battered Dagger",
    secondary: "shield",
    armor: "cloth armor",
    "tool&ammo": "wooden arrows",
  },
  gold: 50,
  name: "Character",
};

export const STEP_NAMES = [
  "RACE",
  "CLASS",
  "ABILITIES",
  "BACKGROUND",
  "PERSONALITY",
  "ALIGNMENT",
  "EQUIPMENT",
  "STARTING GOLD",
  "CHARACTER NAME",
];
export const RACE_GENDER = ["male", "female", "diverse"];
export const RACE = [
  { name: "Arakocra", description: "" },
  { name: "Aasimar", description: "" },
  { name: "Air Genasi", description: "" },
  { name: "Astral Elf", description: "" },
  { name: "Autognome", description: "" },
  { name: "Bugbear", description: "" },
  { name: "Centaur", description: "" },
  { name: "Changeling", description: "" },
  { name: "Deep Gnome", description: "" },
  { name: "Dragonborn", description: "" },
  { name: "Drow", description: "" },
  { name: "Duergar", description: "" },
  { name: "Dwarf", description: "" },
  { name: "Earth Genasi", description: "" },
  { name: "Eladrin", description: "" },
  { name: "Elf", description: "" },
  { name: "Fairy", description: "" },
  { name: "Feral Tiefling", description: "" },
  { name: "Firbolg", description: "" },
  { name: "Fire Genasi", description: "" },
  { name: "Giff", description: "" },
  { name: "Githyanki", description: "" },
  { name: "Githzerai", description: "" },
  { name: "Gnome", description: "" },
  { name: "Goblin", description: "" },
  { name: "Goliath", description: "" },
  { name: "Grung", description: "" },
  { name: "Hadozee", description: "" },
  { name: "Half-Elf", description: "" },
  { name: "Half-Orc", description: "" },
  { name: "Halfling", description: "" },
  { name: "Harengon", description: "" },
  { name: "Hobgoblin", description: "" },
  { name: "Human", description: "" },
  { name: "Kalashtar", description: "" },
  { name: "Kender", description: "" },
  { name: "Kenku", description: "" },
  { name: "Kobold", description: "" },
  { name: "Leonin", description: "" },
  { name: "Lizardfolk", description: "" },
  { name: "Locathah", description: "" },
  { name: "Loxodon", description: "" },
  { name: "Minotaur", description: "" },
  { name: "Orc", description: "" },
  { name: "Owlin", description: "" },
  { name: "Plasmoid", description: "" },
  { name: "Satyr", description: "" },
  { name: "Sea Elf", description: "" },
  { name: "Shadar-Kai", description: "" },
  { name: "Shifter", description: "" },
  { name: "Simic Hybrid", description: "" },
  { name: "Tabaxi", description: "" },
  { name: "Thri-Kreen", description: "" },
  { name: "Tiefling", description: "" },
  { name: "Tortle", description: "" },
  { name: "Triton", description: "" },
  { name: "Vedalken", description: "" },
  { name: "Verdan", description: "" },
  { name: "Warforgerd", description: "" },
  { name: "Water Genasi", description: "" },
  { name: "Yuan-Ti", description: "" },
];

export const ALIGNMENT = [
  {
    name: "true good",
    description: "",
  },
  {
    name: "Lawful Good",
    description: "",
  },
  {
    name: "chaotic good",
    description: "",
  },
  {
    name: "true neutral",
    description: "",
  },
  {
    name: "lawful neutral",
    description: "",
  },
  {
    name: "chaotic neutral",
    description: "",
  },
  {
    name: "true evil",
    description: "",
  },
  {
    name: "lawful evil",
    description: "",
  },
  {
    name: "chaotic evil",
    description: "",
  },
];

export const BACKGROUND = [
  { name: "Arcane Scholar", description: "" },
  { name: "City Watch", description: "" },
  { name: "Criminal Underworld", description: "" },
  { name: "Dungeon Delver", description: "" },
  { name: "Entertainer Extraordinaire", description: "" },
  { name: "Far Traveler", description: "" },
  { name: "Fey-Touched", description: "" },
  { name: "Folk Hero", description: "" },
  { name: "Guild Artisan", description: "" },
  { name: "Haunted Survivor", description: "" },
  { name: "Hermit Mystic", description: "" },
  { name: "Knight Errant", description: "" },
  { name: "Mercenary Veteran", description: "" },
  { name: "Monster Hunter", description: "" },
  { name: "Noble Exile", description: "" },
  { name: "Outlander Wanderer", description: "" },
  { name: "Sage Scholar", description: "" },
  { name: "Sailor of the High Seas", description: "" },
  { name: "Street Urchin", description: "" },
  { name: "Explorer of the Unknown", description: "" },
  { name: "Lost Heir", description: "" },
  { name: "Shadow Agent", description: "" },
  { name: "Spiritual Guide", description: "" },
  { name: "Wilderness Scout", description: "" },
];
export const CLASSES = [
  { name: "Artificer", description: "" },
  { name: "Barbarian", description: "" },
  { name: "Bard", description: "" },
  { name: "Blood Hunter", description: "" },
  { name: "Cleric", description: "" },
  { name: "Druid", description: "" },
  { name: "Fighter", description: "" },
  { name: "Monk", description: "" },
  { name: "Paladin", description: "" },
  { name: "Ranger", description: "" },
  { name: "Rogue", description: "" },
  { name: "Sorcerer", description: "" },
  { name: "Warlock", description: "" },
  { name: "Wizard", description: "" },
];

export const PERSONALITIES = {
  personality: [
    "Adventurous",
    "Brave",
    "Charismatic",
    "Diplomatic",
    "Enigmatic",
    "Gregarigious",
    "Honorable",
    "Equisitive",
  ],
  ideal: [
    "freedom",
    "harmony",
    "justice",
    "knowledge",
    "power",
    "tradition",
    "unity",
    "victory",
  ],
  bond: [
    "family",
    "honor",
    "loyalty",
    "redemption",
    "revenge",
    "service",
    "solitude",
    "treasure",
  ],
  flaw: [
    "addiction",
    "cleptomania",
    "greed",
    "impulsive",
    "jealousy",
    "paranoia",
    "recklessness",
    "temptation",
  ],
};

export const EQUIPMENTS = {
  weapon: [
    "Wooden Sword",
    "Battered Dagger",
    "Wooden Hammer",
    "Wooden Bow",
    "Novice wand",
    "wooden club",
    "battered axe",
    "staff",
  ],
  secondaryweapon: [
    "shield",
    "quiver",
    "cleric symbol",
    "war drum",
    "tarot deck",
    "book of shadows",
    "harp",
    "fishing rod",
  ],
  armour: ["cloth armor", "wooden armor", "leather armor", "plate armor"],
  "tool&ammo": [
    "wooden arrows",
    "thieves tools",
    "health potion",
    "simple compass",
    "animal bait",
    "herbalism kit",
    "disguise kit",
    "holy water",
  ],
};
