export const TIMES = [
  "Ancient Time",
  "Medieval Time",
  "Modern Time",
  "Future Time",
];

export const SETTINGS = [
  "Abyssal Chasm",
  "Arctic Wasteland",
  "Barren Moonscape",
  "Celestial Realm",
  "Crystal Caves",
  "Desert Oasis",
  "Dreamer's Reach",
  "Elemental Plane",
  "Feywild Forest",
  "Floating Sky",
  "Gilded Palace",
  "Gothic Castle",
  "Haunted Marsh",
  "Hidden Valley",
  "Icebound Fortress",
  "Infernal Abyss",
  "Jungle Ruins",
  "Jungle Treetops",
  "Lost Labyrinth",
  "Lunar Colony",
  "Mechanical City",
  "Mystic Marshlands",
  "Necromancer's Tower",
  "Nomadic Wasteland",
  "Ocean Depths",
  "Oracle's Sanctuary",
  "Pirate Cove",
  "Poisoned Bog",
  "Quantum Realm",
  "Rainforest Canopy",
  "Ruined Colosseum",
  "Space Station",
  "Sunken City",
  "Timeless Library",
  "Twisting Canyon",
  "Underdark Caverns",
  "Vaulted Catacombs",
  "Volcanic Island",
  "Whispering Woods",
];
