export const TIMES = [
  "Paleolithic Time",
  "Neolithic Time",
  "Bronze Age Time",
  "Ancient Time",
  "Classical Time",
  "Medieval Time",
  "Renaissance Time",
  "Enlightenment Time",
  "Industrial Time",
  "Modern Time",
  "Present Time",
];

export const SETTINGS = [
  "Abyssal Chasm",
  "Arctic Wasteland",
  "Barren Moonscape",
  "Celestial Realm",
  "Crystal Caves",
  "Desert Oasis",
  "Dreamer's Realm",
  "Elemental Plane",
  "Feywild Forest",
  "Floating Sky",
  "Gilded Palace",
  "Gothic Castle",
  "Haunted Marsh",
  "Hidden Valley",
  "Icebound Fortress",
  "Infernal Abyss",
  "Jungle Ruins",
  "Jungle Treetops",
  "Lost Labyrinth",
  "Lunar Colony",
  "Mechanical City",
  "mystic marshlands",
  "Necromancer's Tower",
  "Nomadic Wasteland",
  "Ocean Depths",
  "Oracle's Sanctuary",
  "Pirate Cove",
  "Poisoned Bog",
  "Quantum Realm",
  "Rainforest Canopy",
  "Ruined Colosseum",
  "Space Station",
  "Sunken City",
  "Timeless Library",
  "Twisting Canyon",
  "Underdark Caverns",
  "Vaulted Catacombs",
  "Volcanic Island",
  "Whispering Woods",
];
